# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/hugo', '-f', 'Dockerfile', '.']
 
images: ['gcr.io/${PROJECT_ID}/hugo']

- name: 'gcr.io/${PROJECT_ID}/hugo'
  args: ['--help']

- name: 'gcr.io/${PROJECT_ID}/hugo'
  entrypoint: ['sh']
  args: ['test.sh']
